\documentclass[article,nojss]{jss}


<<package,include=FALSE,echo=FALSE>>=
options(keep.source = TRUE, width = 60)
packageInfo <- packageDescription("ampCountR")
library(ampCountR)
packageKeywords<-"visualization, amplification, multiple strand displacement, primer design, estimation"
@
%\VignetteIndexEntry{\Sexpr{packageInfo$Package} examples}
%\VignetteDepends{}
%\VignetteKeywords{\Sexpr{packageKeywords}}
%\VignettePackage{\Sexpr{packageInfo$Package}}

\title{\pkg{\Sexpr{packageInfo$Package}} package example (version \Sexpr{packageInfo$Version})}
\author{\Sexpr{packageInfo$Author}}
\Plainauthor{\Sexpr{packageInfo$Author}}

\Address{
  Github: \url{http://github.com/sherrillmix/ampCountR}
}

\Keywords{\Sexpr{packageKeywords}}

\Abstract{
  This is a collection of examples of usage for the \pkg{\Sexpr{packageInfo$Package}} package.
}

\begin{document}
\SweaveOpts{engine=R,eps=FALSE}

\section{General description}

This is an example of using the \pkg{DNAPlotR} package in R.
<<plotDNA, echo=FALSE, eval=FALSE>>=
  set.seed(1234)
  plot(1:10)
@

\begin{figure}[htbp]
\begin{center}
<<showPlotDNA, fig=TRUE, height=4.5, width=8, echo=FALSE>>=
<<plotDNA>>
@
\label{figPlotDNA}
\caption{An example}
\end{center}
\end{figure}

<<plotShortReads, echo=FALSE, eval=FALSE>>=
  set.seed(1234)
  plot(1:20)
@

\begin{figure}[htbp]
\begin{center}
<<showShortReads, fig=TRUE, height=4.5, width=8, echo=FALSE>>=
<<plotShortReads>>
@
\label{figPlotShortReads}
\caption{Another example.}
\end{center}
\end{figure}




\end{document}
